name: e2e-windows

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'website/**'
      - '**/example/**'
      - '!**/example/integration_test/**'
      - '**/flutterfire_ui/**'
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'website/**'
      - '**/example/**'
      - '!**/example/integration_test/**'
      - '**/flutterfire_ui/**'
      - '**.md'

jobs:
  windows:
    runs-on: windows-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      - uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        name: Install Node.js 20
        with:
          node-version: "20"
      - uses: subosito/flutter-action@74af56c5ed2697ba4621264652728e8d217e53d3
        with:
          channel: 'stable'
          cache: true
          cache-key: flutter-${{ runner.os }}
          pub-cache-key: pub-${{ runner.os }}
      - uses: bluefireteam/melos-action@c7dcb921b23cc520cace360b95d02b37bf09cdaa
        with:
          run-bootstrap: false
          melos-version: '3.0.0'
      - name: "Bootstrap package"
        run: melos bootstrap --scope tests && melos bootstrap --scope "cloud_firestore*"
      - name: "Install Tools"
        run: |
          npm install -g firebase-tools
      - name: Start Firebase Emulator and run tests
        run: cd ./.github/workflows/scripts && firebase emulators:exec --project flutterfire-e2e-tests "cd ../../../tests && flutter test .\integration_test\e2e_test.dart -d windows"

# We cannot run the tests but we can still try to build the app because of https://github.com/flutter/flutter/issues/79213
  windows-firestore:
    runs-on: windows-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      - uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        name: Install Node.js 20
        with:
          node-version: "20"
      - uses: subosito/flutter-action@74af56c5ed2697ba4621264652728e8d217e53d3
        with:
          channel: 'stable'
          cache: true
          cache-key: flutter-${{ runner.os }}
          pub-cache-key: pub-${{ runner.os }}
      - uses: bluefireteam/melos-action@c7dcb921b23cc520cace360b95d02b37bf09cdaa
        with:
          run-bootstrap: false
          melos-version: '3.0.0'
      - name: "Bootstrap package"
        run: melos bootstrap --scope tests && melos bootstrap --scope "cloud_firestore*"
      - name: "Install Tools"
        run: |
          npm install -g firebase-tools
      - name: Start Firebase Emulator and run tests
        run: cd ./.github/workflows/scripts && firebase emulators:exec --project flutterfire-e2e-tests "cd ../../../packages/cloud_firestore/cloud_firestore/example && flutter build windows"

